# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/anthonyl/Downloads/vulkan-tutorial

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/anthonyl/Downloads/vulkan-tutorial

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/opt/homebrew/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/opt/homebrew/bin/cpack --config ./CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/anthonyl/Downloads/vulkan-tutorial/CMakeFiles /Users/anthonyl/Downloads/vulkan-tutorial//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/anthonyl/Downloads/vulkan-tutorial/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/anthonyl/Downloads/vulkan-tutorial/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CompileShaders

# Build rule for target.
CompileShaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CompileShaders
.PHONY : CompileShaders

# fast build rule for target.
CompileShaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CompileShaders.dir/build.make CMakeFiles/CompileShaders.dir/build
.PHONY : CompileShaders/fast

#=============================================================================
# Target rules for targets named VulkanTutorial

# Build rule for target.
VulkanTutorial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VulkanTutorial
.PHONY : VulkanTutorial

# fast build rule for target.
VulkanTutorial/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/build
.PHONY : VulkanTutorial/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/CMakeFiles/uninstall.dir/build.make lib/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/src/CMakeFiles/glfw.dir/build.make lib/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/src/CMakeFiles/update_mappings.dir/build.make lib/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named cglm

# Build rule for target.
cglm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cglm
.PHONY : cglm

# fast build rule for target.
cglm/fast:
	$(MAKE) $(MAKESILENT) -f lib/cglm/CMakeFiles/cglm.dir/build.make lib/cglm/CMakeFiles/cglm.dir/build
.PHONY : cglm/fast

src/application.o: src/application.c.o
.PHONY : src/application.o

# target to build an object file
src/application.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/application.c.o
.PHONY : src/application.c.o

src/application.i: src/application.c.i
.PHONY : src/application.i

# target to preprocess a source file
src/application.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/application.c.i
.PHONY : src/application.c.i

src/application.s: src/application.c.s
.PHONY : src/application.s

# target to generate assembly for a file
src/application.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/application.c.s
.PHONY : src/application.c.s

src/data/index.o: src/data/index.c.o
.PHONY : src/data/index.o

# target to build an object file
src/data/index.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/data/index.c.o
.PHONY : src/data/index.c.o

src/data/index.i: src/data/index.c.i
.PHONY : src/data/index.i

# target to preprocess a source file
src/data/index.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/data/index.c.i
.PHONY : src/data/index.c.i

src/data/index.s: src/data/index.c.s
.PHONY : src/data/index.s

# target to generate assembly for a file
src/data/index.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/data/index.c.s
.PHONY : src/data/index.c.s

src/data/vertex.o: src/data/vertex.c.o
.PHONY : src/data/vertex.o

# target to build an object file
src/data/vertex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/data/vertex.c.o
.PHONY : src/data/vertex.c.o

src/data/vertex.i: src/data/vertex.c.i
.PHONY : src/data/vertex.i

# target to preprocess a source file
src/data/vertex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/data/vertex.c.i
.PHONY : src/data/vertex.c.i

src/data/vertex.s: src/data/vertex.c.s
.PHONY : src/data/vertex.s

# target to generate assembly for a file
src/data/vertex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/data/vertex.c.s
.PHONY : src/data/vertex.c.s

src/init/buffers.o: src/init/buffers.c.o
.PHONY : src/init/buffers.o

# target to build an object file
src/init/buffers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/buffers.c.o
.PHONY : src/init/buffers.c.o

src/init/buffers.i: src/init/buffers.c.i
.PHONY : src/init/buffers.i

# target to preprocess a source file
src/init/buffers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/buffers.c.i
.PHONY : src/init/buffers.c.i

src/init/buffers.s: src/init/buffers.c.s
.PHONY : src/init/buffers.s

# target to generate assembly for a file
src/init/buffers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/buffers.c.s
.PHONY : src/init/buffers.c.s

src/init/commands.o: src/init/commands.c.o
.PHONY : src/init/commands.o

# target to build an object file
src/init/commands.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/commands.c.o
.PHONY : src/init/commands.c.o

src/init/commands.i: src/init/commands.c.i
.PHONY : src/init/commands.i

# target to preprocess a source file
src/init/commands.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/commands.c.i
.PHONY : src/init/commands.c.i

src/init/commands.s: src/init/commands.c.s
.PHONY : src/init/commands.s

# target to generate assembly for a file
src/init/commands.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/commands.c.s
.PHONY : src/init/commands.c.s

src/init/device.o: src/init/device.c.o
.PHONY : src/init/device.o

# target to build an object file
src/init/device.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/device.c.o
.PHONY : src/init/device.c.o

src/init/device.i: src/init/device.c.i
.PHONY : src/init/device.i

# target to preprocess a source file
src/init/device.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/device.c.i
.PHONY : src/init/device.c.i

src/init/device.s: src/init/device.c.s
.PHONY : src/init/device.s

# target to generate assembly for a file
src/init/device.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/device.c.s
.PHONY : src/init/device.c.s

src/init/draw_frame.o: src/init/draw_frame.c.o
.PHONY : src/init/draw_frame.o

# target to build an object file
src/init/draw_frame.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/draw_frame.c.o
.PHONY : src/init/draw_frame.c.o

src/init/draw_frame.i: src/init/draw_frame.c.i
.PHONY : src/init/draw_frame.i

# target to preprocess a source file
src/init/draw_frame.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/draw_frame.c.i
.PHONY : src/init/draw_frame.c.i

src/init/draw_frame.s: src/init/draw_frame.c.s
.PHONY : src/init/draw_frame.s

# target to generate assembly for a file
src/init/draw_frame.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/draw_frame.c.s
.PHONY : src/init/draw_frame.c.s

src/init/framebuffers.o: src/init/framebuffers.c.o
.PHONY : src/init/framebuffers.o

# target to build an object file
src/init/framebuffers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/framebuffers.c.o
.PHONY : src/init/framebuffers.c.o

src/init/framebuffers.i: src/init/framebuffers.c.i
.PHONY : src/init/framebuffers.i

# target to preprocess a source file
src/init/framebuffers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/framebuffers.c.i
.PHONY : src/init/framebuffers.c.i

src/init/framebuffers.s: src/init/framebuffers.c.s
.PHONY : src/init/framebuffers.s

# target to generate assembly for a file
src/init/framebuffers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/framebuffers.c.s
.PHONY : src/init/framebuffers.c.s

src/init/graphics_pipeline.o: src/init/graphics_pipeline.c.o
.PHONY : src/init/graphics_pipeline.o

# target to build an object file
src/init/graphics_pipeline.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/graphics_pipeline.c.o
.PHONY : src/init/graphics_pipeline.c.o

src/init/graphics_pipeline.i: src/init/graphics_pipeline.c.i
.PHONY : src/init/graphics_pipeline.i

# target to preprocess a source file
src/init/graphics_pipeline.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/graphics_pipeline.c.i
.PHONY : src/init/graphics_pipeline.c.i

src/init/graphics_pipeline.s: src/init/graphics_pipeline.c.s
.PHONY : src/init/graphics_pipeline.s

# target to generate assembly for a file
src/init/graphics_pipeline.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/graphics_pipeline.c.s
.PHONY : src/init/graphics_pipeline.c.s

src/init/instance.o: src/init/instance.c.o
.PHONY : src/init/instance.o

# target to build an object file
src/init/instance.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/instance.c.o
.PHONY : src/init/instance.c.o

src/init/instance.i: src/init/instance.c.i
.PHONY : src/init/instance.i

# target to preprocess a source file
src/init/instance.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/instance.c.i
.PHONY : src/init/instance.c.i

src/init/instance.s: src/init/instance.c.s
.PHONY : src/init/instance.s

# target to generate assembly for a file
src/init/instance.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/instance.c.s
.PHONY : src/init/instance.c.s

src/init/render_pass.o: src/init/render_pass.c.o
.PHONY : src/init/render_pass.o

# target to build an object file
src/init/render_pass.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/render_pass.c.o
.PHONY : src/init/render_pass.c.o

src/init/render_pass.i: src/init/render_pass.c.i
.PHONY : src/init/render_pass.i

# target to preprocess a source file
src/init/render_pass.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/render_pass.c.i
.PHONY : src/init/render_pass.c.i

src/init/render_pass.s: src/init/render_pass.c.s
.PHONY : src/init/render_pass.s

# target to generate assembly for a file
src/init/render_pass.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/render_pass.c.s
.PHONY : src/init/render_pass.c.s

src/init/swapchain.o: src/init/swapchain.c.o
.PHONY : src/init/swapchain.o

# target to build an object file
src/init/swapchain.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/swapchain.c.o
.PHONY : src/init/swapchain.c.o

src/init/swapchain.i: src/init/swapchain.c.i
.PHONY : src/init/swapchain.i

# target to preprocess a source file
src/init/swapchain.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/swapchain.c.i
.PHONY : src/init/swapchain.c.i

src/init/swapchain.s: src/init/swapchain.c.s
.PHONY : src/init/swapchain.s

# target to generate assembly for a file
src/init/swapchain.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/swapchain.c.s
.PHONY : src/init/swapchain.c.s

src/init/sync_objects.o: src/init/sync_objects.c.o
.PHONY : src/init/sync_objects.o

# target to build an object file
src/init/sync_objects.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/sync_objects.c.o
.PHONY : src/init/sync_objects.c.o

src/init/sync_objects.i: src/init/sync_objects.c.i
.PHONY : src/init/sync_objects.i

# target to preprocess a source file
src/init/sync_objects.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/sync_objects.c.i
.PHONY : src/init/sync_objects.c.i

src/init/sync_objects.s: src/init/sync_objects.c.s
.PHONY : src/init/sync_objects.s

# target to generate assembly for a file
src/init/sync_objects.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/sync_objects.c.s
.PHONY : src/init/sync_objects.c.s

src/init/validation.o: src/init/validation.c.o
.PHONY : src/init/validation.o

# target to build an object file
src/init/validation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/validation.c.o
.PHONY : src/init/validation.c.o

src/init/validation.i: src/init/validation.c.i
.PHONY : src/init/validation.i

# target to preprocess a source file
src/init/validation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/validation.c.i
.PHONY : src/init/validation.c.i

src/init/validation.s: src/init/validation.c.s
.PHONY : src/init/validation.s

# target to generate assembly for a file
src/init/validation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/init/validation.c.s
.PHONY : src/init/validation.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/main.c.s
.PHONY : src/main.c.s

src/utility.o: src/utility.c.o
.PHONY : src/utility.o

# target to build an object file
src/utility.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/utility.c.o
.PHONY : src/utility.c.o

src/utility.i: src/utility.c.i
.PHONY : src/utility.i

# target to preprocess a source file
src/utility.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/utility.c.i
.PHONY : src/utility.c.i

src/utility.s: src/utility.c.s
.PHONY : src/utility.s

# target to generate assembly for a file
src/utility.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanTutorial.dir/build.make CMakeFiles/VulkanTutorial.dir/src/utility.c.s
.PHONY : src/utility.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... CompileShaders"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... VulkanTutorial"
	@echo "... cglm"
	@echo "... glfw"
	@echo "... src/application.o"
	@echo "... src/application.i"
	@echo "... src/application.s"
	@echo "... src/data/index.o"
	@echo "... src/data/index.i"
	@echo "... src/data/index.s"
	@echo "... src/data/vertex.o"
	@echo "... src/data/vertex.i"
	@echo "... src/data/vertex.s"
	@echo "... src/init/buffers.o"
	@echo "... src/init/buffers.i"
	@echo "... src/init/buffers.s"
	@echo "... src/init/commands.o"
	@echo "... src/init/commands.i"
	@echo "... src/init/commands.s"
	@echo "... src/init/device.o"
	@echo "... src/init/device.i"
	@echo "... src/init/device.s"
	@echo "... src/init/draw_frame.o"
	@echo "... src/init/draw_frame.i"
	@echo "... src/init/draw_frame.s"
	@echo "... src/init/framebuffers.o"
	@echo "... src/init/framebuffers.i"
	@echo "... src/init/framebuffers.s"
	@echo "... src/init/graphics_pipeline.o"
	@echo "... src/init/graphics_pipeline.i"
	@echo "... src/init/graphics_pipeline.s"
	@echo "... src/init/instance.o"
	@echo "... src/init/instance.i"
	@echo "... src/init/instance.s"
	@echo "... src/init/render_pass.o"
	@echo "... src/init/render_pass.i"
	@echo "... src/init/render_pass.s"
	@echo "... src/init/swapchain.o"
	@echo "... src/init/swapchain.i"
	@echo "... src/init/swapchain.s"
	@echo "... src/init/sync_objects.o"
	@echo "... src/init/sync_objects.i"
	@echo "... src/init/sync_objects.s"
	@echo "... src/init/validation.o"
	@echo "... src/init/validation.i"
	@echo "... src/init/validation.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utility.o"
	@echo "... src/utility.i"
	@echo "... src/utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/anthonyl/Downloads/vulkan-tutorial/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

